export * as colors from './colors.mjs'
export { getAllHostnames } from './getAllHostnames.mjs'
export { getHostnamesForHost } from './getHostnamesForHost.mjs'
export { mergeConfig } from './mergeConfig.mjs'
export { writeEtcHosts } from './writeEtcHosts.mjs'
export { writeFile } from './writeFile.mjs'
